
install: true
language: objective-c
os: osx
osx_image:  xcode10.1

before_script:
  - mkdir -p build
  - if [ "$LINT" != "" ]; then which swiftlint && brew upgrade swiftlint || brew install swiftlint; fi
  - if [ "$LINT" == "" ]; then Scripts/setup_swift_version.sh; fi
  - if [ "$LINT" == "" ]; then bundle install; fi
  - if [ "$LINT" == "" ]; then bundle exec xcake make; fi
  - if [ "$LINT" == "" ]; then bundle exec pod install; fi

script:
  - Scripts/run_ci.sh

env:
  - SWIFT_VERSION=4.0
  - SWIFT_VERSION=4.2
  - SWIFTC_VERSION=4
  - SWIFTC_VERSION=4.2
  - LINT=true

