before_script:
  - mkdir -p build
  - echo "SWIFT_VERSION=$SWIFT_VERSION.0" > Base.xcconfig 
  - echo "$SWIFT_VERSION.0" > .swift-version
  - cat Base.xcconfig
  - swift --version

script:
  - Scripts/ci_phases/01_lint_project.sh
  - bundle exec pod lib lint --skip-tests
  - Scripts/ci_phases/02_run_tests_macos.sh
  - travis_retry Scripts/ci_phases/03_run_tests_ios.sh
  - swift build -Xswiftc -swift-version -Xswiftc $SWIFT_VERSION
  - swift test -Xswiftc -swift-version -Xswiftc $SWIFT_VERSION -Xswiftc '-DDEBUG'

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.3
      env:
        - SWIFT_VERSION=3
    - os: osx
      language: objective-c
      osx_image: xcode9
      env:
        - SWIFT_VERSION=3
    - os: osx
      language: objective-c
      osx_image: xcode9
      env:
        - SWIFT_VERSION=4