
install: true
language: objective-c
os: osx
osx_image:  xcode10.1

before_script:
  - mkdir -p build
  - [ "$LINT" != "" ] && brew install swifltint || true
  - [ "$LINT" == "" ] && Scripts/setup_swift_version.sh || true
  - [ "$LINT" == "" ] && bundle install || true
  - [ "$LINT" == "" ] && bundle exec xcake make || true
  - [ "$LINT" == "" ] && bundle exec pod install || true

script:
  - Scripts/run_ci.sh

env:
  - SWIFT_VERSION=4.0
  - SWIFT_VERSION=4.2
  - SWIFTC_VERSION=4
  - SWIFTC_VERSION=4.2
  - LINT=true

