
install: true

before_script:
  - mkdir -p build
  - echo "$SWIFT_VERSION.0" > .swift-version
  - swift --version
  - bundle install
  - bundle exec xcake make
  - bundle exec pod install

script:
  - Scripts/ci_phases/01_lint_project.sh
  - Scripts/ci_phases/02_run_tests_macos.sh
  - travis_retry Scripts/ci_phases/03_run_tests_ios.sh
  - swift build -Xswiftc -swift-version -Xswiftc $SWIFT_VERSION
  - swift test -Xswiftc -swift-version -Xswiftc $SWIFT_VERSION -Xswiftc '-DDEBUG'

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10
      env:
        - SWIFT_VERSION=4
    - os: osx
      language: objective-c
      osx_image: xcode10.1
      env:
        - SWIFT_VERSION=4        